# project config name
NAME = 'brainhub'
PROCESSES = 'processes'
THREADS = 'threads'
HOST = 'domain'
PORT = 'port'
PREFIX = 'prefix'
POSTFIX = 'postfix'
HUB = 'hub'
LOG = 'log'
STATIC = 'static'
DEBUG = 'debug'

# api config name
COMMENT = 'comment'
METHODS = 'method'
PROTOCAL = 'protocal'
VERSION = 'version'
RETURN = 'return'
RESULT = 'result'
PARAMS = 'params'
FORMAT = 'format'
DEFAULT = 'default'
ERR_MSG = 'err_msg'
